### ISSUE TITLE
The returned content is not filtered according to parameters

### ISSUE THREAD

**Issue by ChildProdigy** [sfuhrm/radiobrowser4j#117]
Parameter parameter = new Parameter() {
        @Override
         protected void apply(Map<String, String> requestParams) {
                  requestParams.put("countrycode", "CN");
         }};

List<Station> stations = radioBrowser.listStations(Paging.at(0, 10), parameter);

The returned content is not filtered according to parameters

**Comment by sfuhrm** [comment]
You are trying to get a list of stations in country China. The `listStations()` call that you're using is documented to "Get a list of **all** stations.", and that's what it's doing.

What you're looking for is either

```java
List<Station> stations = rb.listStationsBy(Paging.at(0, 10), SearchMode.BYCOUNTRYCODEEXACT, "CN");
```

or `listStationsWithAdvancedSearch()` if you want to search with multiple filters.

Hope this is working for you better.
