### ISSUE TITLE
AdvancedSearchBuilder tag or tagList not work

### ISSUE THREAD

**Issue by ChildProdigy** [sfuhrm/radiobrowser4j#124]
AdvancedSearch.AdvancedSearchBuilder builder = AdvancedSearch.builder();
builder.tagExact(true);
builder.tag("news");

response
=============================1========================================
icon=, name=.977 80s, url=http://playerservices.streamtheworld.com/pls/977_80.pls, type=MP3, tagList=[80s], size=0
=============================2========================================
icon=https://www.0nradio.com/logos/0n-70s_600x600.jpg, name=- 0 N-70s on Radio, url=https://0n-70s.radionetz.de/0n-70s.mp3, type=MP3, tagList=[70er, 70s, oldies, pop], size=0
                                                                       ...

response data tag not correct.

**Comment by sfuhrm** [comment]
Can you please provide a full example unit test?

This test works for me, so I am not sure whether your call is right or I am doing something different than you:

```java
    @Test
    public void listStationsWithAdvancedSearchWithTag() {
        List<Station> stationsList = radioBrowser
                .listStationsWithAdvancedSearch(
                        AdvancedSearch.builder()
                                .tag("news")
                                .tagExact(true)
                                .build())
                .collect(Collectors.toList());

        for (Station station : stationsList) {
            assertThat(station.getTagList(), IsIterableContaining.hasItem("news"));
        }
    }
```

**Comment by ChildProdigy** [comment]
The test just now is normal, but the exact search and the inexact search return the same result.

**Comment by sfuhrm** [comment]
Thanks for verifying!
