### ISSUE TITLE
AdvancedSearchBuilder languageExact not work

### ISSUE THREAD

**Issue by ChildProdigy** [sfuhrm/radiobrowser4j#125]
AdvancedSearch.AdvancedSearchBuilder builder = AdvancedSearch.builder();
builder.language("chinese");
builder.languageExact(true);

response:
cantonese,chinese
chinese
chinese
chinese,english,french,kiswahili,portuguese,spanish

**Comment by sfuhrm** [comment]
Thanks for the issue! If I read your example right, you were expecting that only chinese language stations are being returned when setting the 'language exact' advanced search attribute.

This is not how the HTTP API works. 'Exact' means in the context of the API that only _full_-string matches are returned, not _substring_ matches.
Example: Language search non-exact for 'ch' would return 'chinese' but also 'dutch' language stations. 

As far as I know there is no API call existing to return only chinese language stations.

Feel free to re-open with more explanation if I got you wrong.
