### ISSUE TITLE
Change endpoint for listCountryCodes

### ISSUE THREAD

**Issue by kalwinskidawid** [sfuhrm/radiobrowser4j#150]
Instead of requesting `json/countries` it is better to request `json/countrycodes` - less bytes from the response, faster processing :)
https://github.com/sfuhrm/radiobrowser4j/blob/8f8ac8c7c08207264902d4d24dfd87a4bbd2379e/radiobrowser4j/src/main/java/de/sfuhrm/radiobrowser4j/RadioBrowser.java#L127

```java
return retrieveValueStationCountList("name", "json/countrycodes");
```

**Comment by kalwinskidawid** [comment]
Ouh, api endpoint is deprecated, sorry

**Comment by sfuhrm** [comment]
No worries :)
