### ISSUE TITLE
Unable to use in Android.

### ISSUE THREAD

**Issue by fourofspades** [sfuhrm/radiobrowser4j#7]
Duplicate class javax.activation.ActivationDataFlavor found in modules jetified-jakarta.activation-api-1.2.1 (jakarta.activation:jakarta.activation-api:1.2.1) and jetified-javax.activation-api-1.2.0 (javax.activation:javax.activation-api:1.2.0)

I guess the fix is to update the package to 1.2.1 in this project?

**Comment by fourofspades** [comment]
Hmm, there isn't a 1.2.1  Weird...

**Comment by sfuhrm** [comment]
The `jakarta.activation:jakarta.activation-api` dependency is a transitive dependency from `org.glassfish.jaxb:jaxb-runtime:jar:2.3.2:compile`:

```
mvn dependency:tree
...
[INFO] +- org.glassfish.jaxb:jaxb-runtime:jar:2.3.2:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  +- org.glassfish.jaxb:txw2:jar:2.3.2:compile
[INFO] |  +- com.sun.istack:istack-commons-runtime:jar:3.0.8:compile
[INFO] |  +- org.jvnet.staxex:stax-ex:jar:1.8.1:compile
[INFO] |  +- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.16:compile
[INFO] |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
...
```

The project was not designed to run on Android, but it would be interesting to find out how hard it is.

I don't know your project, but one possibility could be to Maven [exclude](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) the `jakarta.activation:jakarta.activation-api` dependency from the radiobrowser4j dependency in your projects pom. 
Probably you're using Gradle when developing Android apps and will need the Gradle dependency exclusion approach.

Do you want to give it a try?

**Comment by sfuhrm** [comment]
Version 2.0.5 works for me on Android.
It is possible you need to add this to your android section in your app build.gradle file:

```
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/NOTICE.md'
        exclude 'META-INF/LICENSE.md'
        exclude 'META-INF/NOTICE.markdown'
        exclude 'META-INF/ASL2.0'
        exclude("META-INF/*.kotlin_module")
    }
```

**Comment by irvine752** [comment]
I'm having the same issues even with the packaging options above.

Duplicate class javax.inject.Inject found in modules jetified-jakarta.inject-2.6.1 (org.glassfish.hk2.external:jakarta.inject:2.6.1) and jetified-javax.inject-1 (javax.inject:javax.inject:1)
Duplicate class javax.inject.Named found in modules jetified-jakarta.inject-2.6.1 (org.glassfish.hk2.external:jakarta.inject:2.6.1) and jetified-javax.inject-1 (javax.inject:javax.inject:1)
Duplicate class javax.inject.Provider found in modules jetified-jakarta.inject-2.6.1 (org.glassfish.hk2.external:jakarta.inject:2.6.1) and jetified-javax.inject-1 (javax.inject:javax.inject:1)
Duplicate class javax.inject.Qualifier found in modules jetified-jakarta.inject-2.6.1 (org.glassfish.hk2.external:jakarta.inject:2.6.1) and jetified-javax.inject-1 (javax.inject:javax.inject:1)
Duplicate class javax.inject.Scope found in modules jetified-jakarta.inject-2.6.1 (org.glassfish.hk2.external:jakarta.inject:2.6.1) and jetified-javax.inject-1 (javax.inject:javax.inject:1)
Duplicate class javax.inject.Singleton found in modules jetified-jakarta.inject-2.6.1 (org.glassfish.hk2.external:jakarta.inject:2.6.1) and jetified-javax.inject-1 (javax.inject:javax.inject:1)
Duplicate class javax.xml.bind.Binder found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.ContextFinder found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.ContextFinder$1 found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.ContextFinder$2 found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.ContextFinder$3 found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.DataBindingException found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.DatatypeConverter found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.DatatypeConverterImpl found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.DatatypeConverterImpl$CalendarFormatter found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.DatatypeConverterInterface found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.Element found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.GetPropertyAction found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.JAXB found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.JAXB$Cache found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.JAXBContext found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.JAXBContext$1 found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.JAXBElement found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.JAXBElement$GlobalScope found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.JAXBException found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.JAXBIntrospector found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.JAXBPermission found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.MarshalException found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.Marshaller found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.Marshaller$Listener found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.Messages found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.NotIdentifiableEvent found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.ParseConversionEvent found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.PrintConversionEvent found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.PropertyException found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.SchemaOutputResolver found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.TypeConstraintException found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.UnmarshalException found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.Unmarshaller found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.Unmarshaller$Listener found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.UnmarshallerHandler found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.ValidationEvent found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.ValidationEventHandler found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.ValidationEventLocator found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.ValidationException found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.Validator found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.WhiteSpaceProcessor found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.DomHandler found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.W3CDomHandler found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlAccessOrder found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlAccessType found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlAccessorOrder found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlAccessorType found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlAnyAttribute found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlAnyElement found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlAttachmentRef found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlAttribute found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlElement found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlElement$DEFAULT found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlElementDecl found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlElementDecl$GLOBAL found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlElementRef found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlElementRef$DEFAULT found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlElementRefs found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlElementWrapper found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlElements found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlEnum found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlEnumValue found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlID found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlIDREF found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlInlineBinaryData found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlList found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlMimeType found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlMixed found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlNs found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlNsForm found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlRegistry found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlRootElement found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlSchema found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlSchemaType found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlSchemaType$DEFAULT found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlSchemaTypes found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlSeeAlso found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlTransient found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlType found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlType$DEFAULT found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.XmlValue found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.adapters.CollapsedStringAdapter found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.adapters.HexBinaryAdapter found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.adapters.NormalizedStringAdapter found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.adapters.XmlAdapter found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter$DEFAULT found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.annotation.adapters.XmlJavaTypeAdapters found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.attachment.AttachmentMarshaller found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.attachment.AttachmentUnmarshaller found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.helpers.AbstractMarshallerImpl found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.helpers.AbstractUnmarshallerImpl found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.helpers.DefaultValidationEventHandler found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.helpers.Messages found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.helpers.NotIdentifiableEventImpl found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.helpers.ParseConversionEventImpl found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.helpers.PrintConversionEventImpl found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.helpers.ValidationEventImpl found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.helpers.ValidationEventLocatorImpl found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.util.JAXBResult found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.util.JAXBSource found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.util.JAXBSource$1 found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.util.Messages found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)
Duplicate class javax.xml.bind.util.ValidationEventCollector found in modules jetified-jakarta.xml.bind-api-2.3.2 (jakarta.xml.bind:jakarta.xml.bind-api:2.3.2) and jetified-jaxb-api-2.2.12 (javax.xml.bind:jaxb-api:2.2.12)

**Comment by sfuhrm** [comment]
@irvine752 thanks for feedback, will take a look in #9
